# Generated by Django 4.2.27 on 2026-01-30 17:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='filing_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Filing Document',
                'verbose_name_plural': 'Filing Documents',
                'db_table': 'filing_documents',
            },
        ),
        migrations.CreateModel(
            name='GSTFiling',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filing_type', models.CharField(choices=[('GSTR1', 'GSTR-1 - Outward Supplies'), ('GSTR3B', 'GSTR-3B - Summary Return'), ('GSTR9B', 'GSTR-9B - Annual Return')], max_length=10)),
                ('financial_year', models.CharField(max_length=4)),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('filed', 'Filed'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('nil_filing', models.BooleanField(default=False)),
                ('total_taxable_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('declaration_statement', models.TextField(blank=True, null=True)),
                ('declaration_signed', models.BooleanField(default=False)),
                ('declaration_signed_at', models.DateTimeField(blank=True, null=True)),
                ('filing_reference_number', models.CharField(blank=True, max_length=50, null=True)),
                ('filed_at', models.DateTimeField(blank=True, null=True)),
                ('filing_locked', models.BooleanField(default=False)),
                ('lock_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GST Filing',
                'verbose_name_plural': 'GST Filings',
                'db_table': 'gst_filings',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50)),
                ('invoice_date', models.DateField()),
                ('invoice_type', models.CharField(choices=[('b2b', 'B2B'), ('b2c', 'B2C'), ('export', 'Export'), ('debit_note', 'Debit Note'), ('credit_note', 'Credit Note'), ('import', 'Import')], max_length=20)),
                ('counterparty_gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('counterparty_name', models.CharField(blank=True, max_length=255, null=True)),
                ('taxable_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('igst', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cess', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('hsn_code', models.CharField(blank=True, max_length=10, null=True)),
                ('export_port', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_bill_number', models.CharField(blank=True, max_length=50, null=True)),
                ('shipping_bill_date', models.DateField(blank=True, null=True)),
                ('original_invoice_number', models.CharField(blank=True, max_length=50, null=True)),
                ('original_invoice_date', models.DateField(blank=True, null=True)),
                ('note_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='gst_filing.gstfiling')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'gst_invoices',
            },
        ),
        migrations.CreateModel(
            name='GSTR9BDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_outward_supplies', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_inward_supplies', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_tax_collected', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_tax_deposited', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_itc_claimed', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('itc_reversed', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_itc', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('annual_data', models.JSONField(blank=True, null=True)),
                ('auditor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('auditor_membership_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gstr9b_details', to='gst_filing.gstfiling')),
            ],
            options={
                'verbose_name': 'GSTR-9B Details',
                'db_table': 'gstr9b_details',
            },
        ),
        migrations.CreateModel(
            name='GSTR3BDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outward_taxable_supplies', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('outward_tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('inward_supplies', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('itc_reversal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('igst_credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cgst_credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sgst_credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('igst_liability', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cgst_liability', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sgst_liability', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cess_liability', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('interest_payable', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('late_fee_payable', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gstr3b_details', to='gst_filing.gstfiling')),
            ],
            options={
                'verbose_name': 'GSTR-3B Details',
                'db_table': 'gstr3b_details',
            },
        ),
        migrations.CreateModel(
            name='GSTR1Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b2b_invoices_count', models.IntegerField(default=0)),
                ('b2b_invoices_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('b2b_invoices_tax', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('b2c_invoices_count', models.IntegerField(default=0)),
                ('b2c_invoices_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('b2c_invoices_tax', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('export_invoices_count', models.IntegerField(default=0)),
                ('export_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('nil_rated_invoices_count', models.IntegerField(default=0)),
                ('nil_rated_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('debit_notes_count', models.IntegerField(default=0)),
                ('credit_notes_count', models.IntegerField(default=0)),
                ('net_notes_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('invoice_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gstr1_details', to='gst_filing.gstfiling')),
            ],
            options={
                'verbose_name': 'GSTR-1 Details',
                'db_table': 'gstr1_details',
            },
        ),
    ]
