# Generated by Django 4.2.27 on 2026-01-30 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gst_filing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gstfiling',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gst_filings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filingdocument',
            name='filing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='gst_filing.gstfiling'),
        ),
        migrations.AlterUniqueTogether(
            name='gstfiling',
            unique_together={('user', 'filing_type', 'financial_year', 'month')},
        ),
    ]
