# Generated by Django 4.2.27 on 2026-01-31 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst_filing', '0002_add_user_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gstfiling',
            name='financial_year',
            field=models.CharField(max_length=9),
        ),
    ]
