# Generated by Django 4.2.27 on 2026-01-31 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ITRFiling',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filing_type', models.CharField(choices=[('ITR1', 'ITR-1 (Sahaj)'), ('ITR2', 'ITR-2'), ('ITR3', 'ITR-3'), ('ITR4', 'ITR-4 (Sugam)')], max_length=10)),
                ('financial_year', models.CharField(max_length=7)),
                ('assessment_year', models.CharField(max_length=7)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_verification', 'Pending Verification'), ('verified', 'Verified'), ('filed', 'Filed'), ('rejected', 'Rejected')], default='draft', max_length=25)),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_tax_liability', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_tax_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax_due', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('acknowledgment_number', models.CharField(blank=True, max_length=50, null=True)),
                ('filed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itr_filings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ITR Filing',
                'verbose_name_plural': 'ITR Filings',
                'db_table': 'itr_filings',
                'unique_together': {('user', 'financial_year', 'filing_type')},
            },
        ),
        migrations.CreateModel(
            name='ITRDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('form_16', 'Form 16'), ('bank_statement', 'Bank Statement'), ('investment_proof', 'Investment Proof'), ('pan_card', 'PAN Card'), ('aadhaar_card', 'Aadhaar Card'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='itr_documents/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('filing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='itr_system.itrfiling')),
            ],
            options={
                'verbose_name': 'ITR Document',
                'verbose_name_plural': 'ITR Documents',
                'db_table': 'itr_documents',
            },
        ),
        migrations.CreateModel(
            name='ITR1Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('house_property_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('other_sources_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('deduction_80c', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('deduction_80d', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax_payable', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('rebate_87a', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('surcharge', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('health_education_cess', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('form_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='itr1_details', to='itr_system.itrfiling')),
            ],
            options={
                'verbose_name': 'ITR-1 Detail',
                'verbose_name_plural': 'ITR-1 Details',
                'db_table': 'itr1_details',
            },
        ),
    ]
