# Generated by Django 4.2.27 on 2026-01-31 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TDSReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('return_type', models.CharField(choices=[('24Q', 'Form 24Q - Salary'), ('26Q', 'Form 26Q - Non-Salary'), ('27Q', 'Form 27Q - NRI Payments'), ('27EQ', 'Form 27EQ - TCS')], max_length=10)),
                ('financial_year', models.CharField(max_length=7)),
                ('quarter', models.CharField(choices=[('Q1', 'Q1 (Apr-Jun)'), ('Q2', 'Q2 (Jul-Sep)'), ('Q3', 'Q3 (Oct-Dec)'), ('Q4', 'Q4 (Jan-Mar)')], max_length=5)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Verification'), ('verified', 'Verified'), ('filed', 'Filed'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('tan_number', models.CharField(max_length=10)),
                ('deductor_name', models.CharField(max_length=200)),
                ('total_deducted', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_deposited', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('acknowledgment_number', models.CharField(blank=True, max_length=50, null=True)),
                ('filed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tds_returns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tds_returns',
                'unique_together': {('user', 'return_type', 'financial_year', 'quarter')},
            },
        ),
        migrations.CreateModel(
            name='TDSDeductee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pan', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('section_code', models.CharField(max_length=10)),
                ('date_of_payment', models.DateField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tds_deducted', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tds_deposited', models.DecimalField(decimal_places=2, max_digits=15)),
                ('challan_number', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tds_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductees', to='tds_filing.tdsreturn')),
            ],
            options={
                'db_table': 'tds_deductees',
            },
        ),
        migrations.CreateModel(
            name='TDSChallan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('challan_number', models.CharField(max_length=20)),
                ('bsr_code', models.CharField(max_length=10)),
                ('challan_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('challan_type', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tds_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challans', to='tds_filing.tdsreturn')),
            ],
            options={
                'db_table': 'tds_challans',
            },
        ),
    ]
