# Generated by Django 4.2.27 on 2026-01-31 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(choices=[('company_incorporation', 'Company Incorporation'), ('fssai_registration', 'FSSAI Registration'), ('msme_registration', 'MSME/Udyam Registration'), ('pan_application', 'PAN Application'), ('tan_application', 'TAN Application')], max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('documents_pending', 'Documents Pending'), ('under_review', 'Under Review'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('application_data', models.JSONField(default=dict)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('application_reference', models.CharField(max_length=50, unique=True)),
                ('certificate_number', models.CharField(blank=True, max_length=100, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'service_applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('id_proof', 'ID Proof'), ('address_proof', 'Address Proof'), ('photo', 'Photograph'), ('moa', 'MOA'), ('aoa', 'AOA'), ('rent_agreement', 'Rent Agreement'), ('noc', 'NOC'), ('other', 'Other')], max_length=20)),
                ('document_name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='service_documents/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='business_services.serviceapplication')),
            ],
            options={
                'db_table': 'service_documents',
            },
        ),
        migrations.CreateModel(
            name='PANTANApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_type', models.CharField(choices=[('pan_new', 'New PAN'), ('pan_correction', 'PAN Correction'), ('tan_new', 'New TAN'), ('tan_correction', 'TAN Correction')], max_length=20)),
                ('applicant_name', models.CharField(max_length=200)),
                ('father_name', models.CharField(blank=True, max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('existing_pan', models.CharField(blank=True, max_length=10)),
                ('existing_tan', models.CharField(blank=True, max_length=10)),
                ('issued_pan', models.CharField(blank=True, max_length=10, null=True)),
                ('issued_tan', models.CharField(blank=True, max_length=10, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pantan_details', to='business_services.serviceapplication')),
            ],
            options={
                'db_table': 'pantan_applications',
            },
        ),
        migrations.CreateModel(
            name='MSMERegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise_name', models.CharField(max_length=200)),
                ('enterprise_type', models.CharField(choices=[('micro', 'Micro'), ('small', 'Small'), ('medium', 'Medium')], max_length=20)),
                ('nic_code', models.CharField(max_length=10)),
                ('major_activity', models.CharField(max_length=200)),
                ('plant_address', models.TextField()),
                ('investment_in_plant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('annual_turnover', models.DecimalField(decimal_places=2, max_digits=15)),
                ('udyam_number', models.CharField(blank=True, max_length=25, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='msme_details', to='business_services.serviceapplication')),
            ],
            options={
                'db_table': 'msme_registrations',
            },
        ),
        migrations.CreateModel(
            name='FSSAIRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_type', models.CharField(choices=[('basic', 'Basic Registration'), ('state', 'State License'), ('central', 'Central License')], max_length=20)),
                ('business_name', models.CharField(max_length=200)),
                ('food_category', models.CharField(max_length=200)),
                ('premise_address', models.TextField()),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=15)),
                ('annual_turnover', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fssai_license_number', models.CharField(blank=True, max_length=20, null=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fssai_details', to='business_services.serviceapplication')),
            ],
            options={
                'db_table': 'fssai_registrations',
            },
        ),
        migrations.CreateModel(
            name='CompanyIncorporation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_name_1', models.CharField(max_length=200)),
                ('proposed_name_2', models.CharField(blank=True, max_length=200)),
                ('proposed_name_3', models.CharField(blank=True, max_length=200)),
                ('company_type', models.CharField(choices=[('pvt_ltd', 'Private Limited'), ('llp', 'LLP'), ('opc', 'One Person Company'), ('public', 'Public Limited'), ('section_8', 'Section 8 Company')], max_length=20)),
                ('authorized_capital', models.DecimalField(decimal_places=2, max_digits=15)),
                ('paid_up_capital', models.DecimalField(decimal_places=2, max_digits=15)),
                ('registered_address', models.TextField()),
                ('business_activity', models.TextField()),
                ('directors_data', models.JSONField(default=list)),
                ('name_approval_status', models.CharField(blank=True, max_length=50, null=True)),
                ('cin', models.CharField(blank=True, max_length=25, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_details', to='business_services.serviceapplication')),
            ],
            options={
                'db_table': 'company_incorporations',
            },
        ),
    ]
